fix: keyboard manager initializedKey
windingwind/zotero-plugin-toolkit pull request #43
Opened 2024-01-15 16:47 UTC by windingwind

2024-01-15 16:48 UTC, windingwind commented
@northword @volatile-static

2024-01-16 02:01 UTC, volatile-static requested changes
我只看了patcher的部分

- [x] `PatchData`或许叫**Info**或者**Params**更贴切一些？
- [ ] `FunctionsOf`这种类型定义比较通用，我还是建议从更高层的类型定义文件里导入一下

2024-01-16 02:03 UTC, volatile-static commented on src/helpers/patch.ts
> +        }
不过这样的弊端可能是，只要一个插件不处理异常，所有下游patch就都不会执行

2024-01-16 02:05 UTC, windingwind commented on src/helpers/patch.ts
> +        }
在getField之类的地方抛出未处理的异常会直接触发zo的异常处理，整个库变成提示出现异常需要重启，不方便新上手的人调试？
同时如果插件损坏，会导致整个用不了

2024-01-16 02:06 UTC, volatile-static commented on src/helpers/patch.ts
> +        }
这样的话，看来还是不要抛出的好

2024-01-16 02:13 UTC, windingwind commented on src/helpers/patch.ts
> +        }
一般异常在patch函数内部处理即可，不必要放到这里处理；这里只是一个后备保险

2024-01-16 02:24 UTC, volatile-static approved these changes

2024-01-16 02:27 UTC, merged